# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20161121_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
