# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20161121_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='current_ask_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='current_bid_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='minimum_volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='pair',
            name='num_of_trades',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='volume',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
