# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20161121_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='survives_harvest',
            field=models.BooleanField(default=False),
        ),
    ]
