# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_pair_survives_harvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='current_ask_volume',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pair',
            name='current_bid_volume',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pair',
            name='num_of_trades',
            field=models.IntegerField(null=True),
        ),
    ]
