# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20161122_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='minimum_volume',
            new_name='minimum_ask_volume',
        ),
        migrations.AddField(
            model_name='pair',
            name='minimum_bid_volume',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
    ]
