# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20161122_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='groi',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='max_investment',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='nroi',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
