# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20161122_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chainpair',
            name='pair',
        ),
        migrations.AddField(
            model_name='chainpair',
            name='pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analysis.Pair'),
        ),
    ]
